### ISSUE TITLE
Create multiple branches with different config

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/service-ethereum-erc20#4]
## Problem

This is a configurable service. The default config is for Tron Token on Mainnet.
It's super boring to have to git clone and edit the config file to change the config.

## Solution

Create multiple branches that contain different config for different ERC20 and different net (ropsten, kovan, main).

Then, user should be able to run the command to download the service with the right config, eg:

```
mesg-core service deploy https://github.com/mesg-foundation/service-ethereum-erc20#mesg-token-ropsten
```

**Comment by NicolasMahe** [comment]
The PR #5 make this service generic, so no need to configure the service for a specific ERC20.

But, it will be nice to have one config per Ethereum network (mainnet, testnet, ropsten).
And also maybe different ethereum connection. For now it's using infura, but it will be nice to start a light node in a separate docker.

**Comment by antho1404** [comment]
Definitely a good idea to have the different networks on different branches 👍 we could use `mesg-core service deploy https://github.com/mesg-foundation/service-ethereum-erc20#mainnet / #rinkeby...` that's pretty good

**Comment by NicolasMahe** [comment]
Done
